# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostAndFound',
            new_name='LostAndFoundRecords',
        ),
        migrations.RenameModel(
            old_name='CriminalRecord',
            new_name='PoliceCriminalRecord',
        ),
    ]
