# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0002_auto_20190126_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedusers',
            options={'verbose_name': 'List Of Authorized Users', 'verbose_name_plural': 'List Of Authorized Users'},
        ),
        migrations.AlterModelOptions(
            name='childcategory',
            options={'verbose_name': 'Child Category', 'verbose_name_plural': 'Child Category'},
        ),
        migrations.AlterModelOptions(
            name='childgender',
            options={'verbose_name': 'Child Gender', 'verbose_name_plural': 'Child Gender'},
        ),
        migrations.AlterModelOptions(
            name='lostandfoundrecords',
            options={'verbose_name': 'Lost and Found records', 'verbose_name_plural': 'Lost and Found records'},
        ),
        migrations.AlterModelOptions(
            name='pendingusers',
            options={'verbose_name': 'List Of Pending Users', 'verbose_name_plural': 'List Of Pending Users'},
        ),
        migrations.AlterModelOptions(
            name='policecriminalrecord',
            options={'verbose_name': 'Police Criminal Records', 'verbose_name_plural': 'Police Criminal Records'},
        ),
        migrations.AlterModelOptions(
            name='registeredchildren',
            options={'verbose_name': 'Child Registration Information', 'verbose_name_plural': 'Child Registration Information'},
        ),
        migrations.AlterField(
            model_name='lostandfoundrecords',
            name='imageOfChild1',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found_records/'),
        ),
        migrations.AlterField(
            model_name='lostandfoundrecords',
            name='imageOfChild2',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found_records/'),
        ),
        migrations.AlterField(
            model_name='lostandfoundrecords',
            name='imageOfChild3',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found_records/'),
        ),
        migrations.AlterField(
            model_name='policecriminalrecord',
            name='imageOfChild1',
            field=models.ImageField(blank=True, null=True, upload_to='criminal_records/'),
        ),
        migrations.AlterField(
            model_name='policecriminalrecord',
            name='imageOfChild2',
            field=models.ImageField(blank=True, null=True, upload_to='criminal_records/'),
        ),
        migrations.AlterField(
            model_name='policecriminalrecord',
            name='imageOfChild3',
            field=models.ImageField(blank=True, null=True, upload_to='criminal_records/'),
        ),
    ]
