# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0003_auto_20190126_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policecriminalrecord',
            old_name='imageOfChild1',
            new_name='imageOfChild',
        ),
        migrations.RemoveField(
            model_name='lostandfoundrecords',
            name='imageOfChild2',
        ),
        migrations.RemoveField(
            model_name='lostandfoundrecords',
            name='imageOfChild3',
        ),
        migrations.RemoveField(
            model_name='policecriminalrecord',
            name='imageOfChild2',
        ),
        migrations.RemoveField(
            model_name='policecriminalrecord',
            name='imageOfChild3',
        ),
    ]
