# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0005_auto_20190127_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredchildren',
            name='criminalRecord',
        ),
        migrations.AddField(
            model_name='registeredchildren',
            name='birthMark',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
