# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0006_auto_20190128_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredchildren',
            name='childFoundTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
