# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0007_auto_20190130_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policecriminalrecord',
            name='criminalRecord',
        ),
        migrations.AlterField(
            model_name='registeredchildren',
            name='parentsEmployment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeredchildren',
            name='schoolAdmission',
            field=models.BooleanField(default=False),
        ),
    ]
