# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0008_auto_20190130_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policecriminalrecord',
            name='category',
        ),
    ]
