# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0009_remove_policecriminalrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredchildren',
            name='imageOfChild',
            field=models.ImageField(blank=True, null=True, upload_to='child_registrations/'),
        ),
    ]
