# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0010_auto_20190130_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedusers',
            name='user',
        ),
        migrations.AlterField(
            model_name='registeredchildren',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthorizedUsers',
        ),
    ]
