# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0011_auto_20190130_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingusers',
            name='otpCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
