# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0012_pendingusers_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingusers',
            name='user',
        ),
        migrations.AddField(
            model_name='pendingusers',
            name='userName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
