# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0013_auto_20190203_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheckup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicalCheckupStatus', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuVeNiLeApP.RegisteredChildren')),
            ],
        ),
    ]
