# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0014_medicalcheckup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanageNgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicalcheckup',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JuVeNiLeApP.RegisteredChildren'),
        ),
        migrations.AddField(
            model_name='medicalcheckup',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JuVeNiLeApP.OrphanageNgo'),
        ),
    ]
