# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JuVeNiLeApP', '0015_auto_20190323_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcheckup',
            name='medicalReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
